baseurl = "https://blog.clopend.com/"
title = "Clopend"
author = "Clopend"
canonifyurls = true
languagecode = "zh-Hans"

publishDir = "docs"

[params]
  sitename = "Clopend"
  slogan = "Less is More"
  github = "https://github.com/clopend"

