name: Publish Blog

on:
  push:
    branchs:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Blog
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'

    - name: Build
      run: hugo --minify

    - name: Deploy Blog
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: ./docs
