name: Publish Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Public
      uses: actions/checkout@master
      with:
        repository: huangmeihui/huangmeihui.github.io
        path: ./public
        persist-credentials: false
        fetch-depth: 0
    - uses: textbook/git-checkout-submodule-action@2.1.1
    - uses: jakejarvis/hugo-build-action@master
    - name: Add & Commit
      run: |
        git config --global user.name huangmeihui
        git config --global user.email huangmeihui@hotmail.com
        cd ./public
        git add .
        git commit -m "update"
    - name: Deploy Blog
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        repository: huangmeihui/huangmeihui.github.io
        directory: ./public
